# Generated by Django 4.1.5 on 2023-01-28 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SosRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тел. номер')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shelters.shelter', verbose_name='Шелтер')),
            ],
            options={
                'verbose_name': 'SOS заявка',
                'verbose_name_plural': 'SOS заявки',
            },
        ),
    ]
