# Generated by Django 4.1.5 on 2023-01-29 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sos_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sosrecord',
            options={'verbose_name': 'Заявка SOS', 'verbose_name_plural': 'Заявки SOS'},
        ),
    ]
