# Generated by Django 4.1.5 on 2023-01-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos_records', '0002_alter_sosrecord_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosrecord',
            name='status',
            field=models.IntegerField(choices=[(1, 'В очереди'), (2, 'В процессе'), (3, 'Закрыто'), (4, 'Отклонено')], default=1),
            preserve_default=False,
        ),
    ]
