# Generated by Django 4.1.5 on 2023-01-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos_records', '0003_sosrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosrecord',
            name='status',
            field=models.IntegerField(choices=[(1, 'В очереди'), (2, 'В процессе'), (3, 'Закрыто'), (4, 'Отклонено')], default=1),
        ),
    ]
