# Generated by Django 4.1.5 on 2023-01-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsernameId',
            fields=[
                ('username', models.CharField(max_length=128)),
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
