# Generated by Django 4.1.5 on 2023-01-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernameid',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usernameid',
            name='telegram_id',
            field=models.BigIntegerField(),
        ),
    ]
