# Generated by Django 4.1.5 on 2023-01-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_usernameid_id_alter_usernameid_telegram_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernameid',
            options={'verbose_name': 'Привязка юзернейма и ID', 'verbose_name_plural': 'Привязки юзернейма и ID'},
        ),
        migrations.AlterField(
            model_name='usernameid',
            name='telegram_id',
            field=models.BigIntegerField(verbose_name='Телеграм ID'),
        ),
        migrations.AlterField(
            model_name='usernameid',
            name='username',
            field=models.CharField(max_length=128, verbose_name='Юзернейм'),
        ),
    ]
